### ISSUE TITLE
Learn git with Codeschool tutorial

### ISSUE THREAD

**Issue by RabeaGleissner** [Harri24/apprenticeship#3]
https://www.pluralsight.com/courses/code-school-git-real

**Comment by Harri24** [comment]
This was not as great, maybe because git is a little tricky to first get your head around, I found this tutorial both rushed and sluggish - I felt that I was unable to really follow along - and doing it myself always helps, so instead I just ended up getting very confused and annoyed that I wasn't picking up git instantly. To combat this I first googled for lots of online guides that attempted to explain what was involved when using git - though these just proved to muddle me further (Tuesday was not a great day!) Thus I instead googled for the best basic tutorials that explained git and found a comprehensive list of some suggestions. Not wanting to pay I first tried out the udemy intro to git 'git started with git hub' this was the tits, he really stripped it down and put all the other information I had consumed into context. BUT this course (probably because its free) is way to short - so I purchased the full course (£10) bit of spurge and probably not what we should include in the scheme guide - But I am almost finished (its a lot longer) and I feel so much more confident and secure when it comes to use of the command line, git, github and the terminal. Also I'm not very good at moving on from something unless I'm really confident in it hence why I have been spending way too long on this task......
